---

- name: setup group
  group:
    name: "{{ mysql_group }}"
    system: true

- name: setup user
  user:
    name: "{{ mysql_user }}"
    system: true
    createhome: false
    group: "{{ mysql_group }}"
